name: Variable test

on:
  release:
    types: [released]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: test variable value
      run: "echo ${{ env.TEST }}"
